### ISSUE TITLE
Expose user quotas

### ISSUE THREAD

**Issue by thomasem** [getcarina/carina#101]
Soon the quotas endpoint will be query-able for user quotas. Might be nice to allow this in the carina CLI as well so users can see what their current limits are.

**Comment by rgbkrk** [comment]
Ah, what's the API?

**Comment by thomasem** [comment]
When we push the change out it'll be `GET /quotas/<username>` and should return
```json
{
  "max_clusters": 3,
  "max_nodes_per_cluster": 3
}
```

**Comment by rgbkrk** [comment]
That's easy enough to add to libcarina, I'll be happy to add it.

**Comment by thomasem** [comment]
Actually, I'm starting to learn Go. Would you be at all bothered if I assigned myself and took a stab at it?

**Comment by rgbkrk** [comment]
Gosh, feel free. Happy to help you along in that. It's better to have more people than me involved.

**Comment by thomasem** [comment]
Sweet. Thanks!

**Comment by thomasem** [comment]
Released in https://github.com/getcarina/carina/releases/tag/v1.3.0

**Comment by rgbkrk** [comment]
:boom:
