### ISSUE TITLE
Binaries for carina v1.2.1 not at path shown

### ISSUE THREAD

**Issue by adrianotto** [getcarina/carina#102]
If I start with carina1.1.1, I see this:

```
Adrians-MBP:~ aotto$ carina ls
# A new version of the Carina client is out, go get it
# You're on 1.1.1 and the latest is 1.2.1
# https://github.com/getcarina/carina/releases
```

However, If I visit the URL above, no binaries are present for version 1.2.1. However, If I download using:

```
curl -L https://download.getcarina.com/carina/latest/$(uname -s)/$(uname -m)/carina -o carina
```

Then I get v1.2.1. I suggest we change the URL returned by the client when there is a new version to reflect https://github.com/getcarina/carina/blob/master/README.md#installation or some pretty variant of that, and put the new binaries at the URL it currently references.

**Comment by rgbkrk** [comment]
We either need centralized installation instructions for the release or deep conditional checks. Right now our "how to upgrade" is still embedded in that releases page (in case it changes release to release).

If you have an idea of the text, feel free to submit a PR.

**Comment by carolynvs** [comment]
The upcoming beta cli will now link to https://getcarina.com/betadocs/docs/reference/carina-cli#upgrade for instructions on how to upgrade.
