### ISSUE TITLE
carina get --wait always waits 40 seconds before doing anything

### ISSUE THREAD

**Issue by carolynvs** [getcarina/carina#105]
1. Run `carina create --wait foobar`
2. Run `carina ls` and note that the foobar cluster is active.
3. Run `carina get foobar` and it returns quickly.
4. Run `carina get --wait foobar` and it takes over 40 seconds before it returns.

Looks like all the awaitable commands use the same implementation, and it always sleeps for a 40 second "fudge factor" before doing anything. 

https://github.com/getcarina/carina/blob/master/main.go#L613

I assume that this was so that the client doesn't immediately query for cluster status after a `carina create` but it doesn't make sense for `carina get`.

Reported by @vikomall in https://github.com/getcarina/feedback/issues/66

**Comment by rgbkrk** [comment]
Crap. Yeah the fugde factor should only be applied to create. However, I think we could safely remove the fudge factor since we only poll every 15 seconds.
