### ISSUE TITLE
dvm resources missing

### ISSUE THREAD

**Issue by Contextualist** [getcarina/carina#111]
When I tried to install the latest dvm using [install.ps1](https://download.getcarina.com/dvm/latest/install.ps1), I got HTTP error 404 at the step trying to download [dvm-helper.exe for Windows x86](https://download.getcarina.com/dvm/0.6.2/Windows/i386/dvm-helper.exe).

I checked and found that dvm-helper.exe and dvm-helper.exe.sha256 for Windows x86 are missing (those for x64 are fine, though), 
i.e. 
https://download.getcarina.com/dvm/0.6.2/Windows/i386/dvm-helper.exe   and
https://download.getcarina.com/dvm/0.6.2/Windows/i386/dvm-helper.exe.sha256

**Comment by carolynvs** [comment]
@Contextualist Thanks for bringing this up! I have deployed a new release (0.6.4) which includes 32-bit binaries for Windows.

Would you please retry running the PowerShell installation and if you run into any problems, let me know!

```
Invoke-WebRequest https://download.getcarina.com/dvm/latest/install.ps1 -UseBasicParsing | Invoke-Expression
```

**Comment by Contextualist** [comment]
@carolynvs Thanks so much for providing dvm for 32-bit windows! dvm-helper.exe runs smoothly, but it seems that `docker` command or alias is not properly set after `dvm use` finishes running.  BTW, `$env:USERPROFILE\.dvm\bin\docker\1.11.2\docker.exe` is completely OK.

**Comment by carolynvs** [comment]
First let's level-set and sure you are loading dvm properly:

1. Installed dvm using the powershell snippet from the readme.
2. Updated your `$profile` to load `dvm.ps1` automatically. My profile script is located at `C:\Users\carolyn\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1` and contains `. C:\Users\carolyn\.dvm\dvm.ps1`. Your profile may be in a different location.
3. I use the `dvm` powershell function directly, not dvm-helper.exe.

If that matches what you are doing, then let's try running in debug mode and reply back with the output. Maybe something will jump out at us. 😄 

```powershell
> dvm --debug use 1.11.2

The dvm home directory is: C:\Users\carolyn\.dvm
dvm use 1.11.2
Checking if version is installed: 1.11.2
Checking version: system (1.6.1)
Checking version: 1.11.2
Version 1.11.2 is installed
Writing to C:\Users\carolyn\.dvm\.tmp\dvm-output.ps1...
$env:PATH="C:\Users\carolyn\.dvm\bin\docker\1.11.2;[REDACTED]"
Now using Docker 1.11.2

> echo $env:PATH
C:\Users\carolyn\.dvm\bin\docker\1.11.2;[REDACTED]
```

**Comment by Contextualist** [comment]
Ah, thanks for your help, there's no problem with dvm. I checked your steps and found that I had forgotten to source the dvm environment.
