### ISSUE TITLE
Perform usability testing on credentials download

### ISSUE THREAD

**Issue by rgbkrk** [getcarina/carina#32]
Personally, I'm a bit annoyed with the structure I have laid out for credentials for accounts with Carina and that `carina` doesn't natively know how I have it set up. It may make sense to integrate properly with docker machine (though we'll still have `grow` and some commands separately in this cli). That would, at the very least, mean credentials get dumped in exactly one place.

In lieu of that, I would at least like to figure out what the right name for this command is and what the default experience should be. It's pretty slick right now, but I can tell it's... not quite what we want.

**Comment by annegentle** [comment]
I get this and it confused me a little bit. 

#
# Credentials written to /tmp/
#
source "/tmp/docker.env"
# Run the command above or eval a subshell with your arguments to carina
#   eval "$( carina command... )"

The `eval "$( carina command... )"` is what's confusing to me. I understand how to use that for docker env, what does it mean for carina env?

**Comment by rgbkrk** [comment]
Is it the command part? That's because I wasn't sure how to get their raw command into where `carina command` was.

**Comment by rgbkrk** [comment]
I'm going to try something and post back with new output, let me know how it looks in a little bit.

**Comment by rgbkrk** [comment]
Ok, went back to this since I wasn't sure what prevented me from including the args directly here. It was because the path specified by users might have spaces in them, which we'd have to escape. If I go ahead and escape most of them, it works just fine:

```
$ eval "$( carina credentials tmpnbtrial --path ~/tmp )"
21:33:12 {sourcery *} kyle6475@lack ~/code/src/github.com/rackerlabs/carina$ carina credentials tmpnbtrial --path ~/tmp
#
# Credentials written to /Users/kyle6475/tmp/
#
source "/Users/kyle6475/tmp/docker.env"
# Run the command above or eval a subshell like so
#   eval "$( carina "credentials" "tmpnbtrial" "--path" "/Users/kyle6475/tmp" )"
```

**Comment by rgbkrk** [comment]
I'll come back again to this to see if the cli tooling used here provides something useful out of the parse context (right now I'm not seeing all of it).

**Comment by rgbkrk** [comment]
How's this @annegentle?

```
carina credentials morecowbell --path "/tmp/path with space/morecowbell"
#
# Credentials written to /tmp/path with space/morecowbell/
#
source "/tmp/path with space/morecowbell/docker.env"
# Run the command above or eval a subshell like so
#   eval "$( carina credentials morecowbell --path "/tmp/path with space/morecowbell"  )"
```

**Comment by rgbkrk** [comment]
Alternatively, we could just only spit out the source line for now.

**Comment by rgbkrk** [comment]
How's:

```bash
$ carina credentials morecowbell --path "/tmp/path with space/morecowbell"
#
# Credentials written to "/tmp/path with space/morecowbell/"
#
source "/tmp/path with space/morecowbell/docker.env"
# Run the command above or eval a subshell with your args
#   eval "$( carina credentials ...  )"
```

**Comment by rgbkrk** [comment]
Now that we have `carina env` via #52 as well as #34, I'll mark this as closed and we can re-open it later.
