### ISSUE TITLE
invalid character error listing clusters

### ISSUE THREAD

**Issue by carolynvs** [getcarina/carina#40]
I am using Caesious Caelum. When I run `carina list` (with no clusters), I get this error:

```
carina.exe: error: invalid character '<' looking for beginning of value, try --help
```

**Comment by rgbkrk** [comment]
Fixed by https://github.com/getcarina/libcarina/pull/9 and some backend re-jiggering.

**Comment by carolynvs** [comment]
:+1: Thanks!
