### ISSUE TITLE
Carina CLI client very sensitive to network latency

### ISSUE THREAD

**Issue by lowescott** [getcarina/carina#45]
Hi all, I was just giving the Carina CLI client a go this morning from the OpenStack Summit in Tokyo, and noted that the client is _extremely_ sensitive to network latency. This might necessitate changes in how the client handles retries when faced with less-than-ideal network performance. Let me know what sorts of tests or additional information I can provide that might help here.

**Comment by jnoller** [comment]
@lowescott Thank you - that's precisely the sort of thing we want to know about. Pretty sure this is descriptive enough

**Comment by rgbkrk** [comment]
Hey @lowescott I've done a bit of work in caching the auth tokens in #56 as well as dialing our update check down #54. The next step I'll take on this is bumping up the timeout for both DNS and TCP connections with our servers.

**Comment by rgbkrk** [comment]
Care to try out the 0.9.1 release?

**Comment by lowescott** [comment]
@rgbkrk Yep, I'll give it a try over the next few days while recovering from oral surgery. :-)

**Comment by rgbkrk** [comment]
Yikes! Feel better soon and best of luck.

**Comment by rgbkrk** [comment]
Things have been going well this since 0.9.1. Feel free to re-open if there are issues.
