### ISSUE TITLE
Feature request: Streamline use of "carina credentials" command

### ISSUE THREAD

**Issue by lowescott** [getcarina/carina#46]
I may have missed how to do this, but it would be great if there was a way to streamline the use of `carina credentials` to make it easier to use with the Docker client. I'm thinking of the way that Docker Machine does it, so that a single command will set up Docker:

`eval "$(docker-machine env engine-01)"`

I'd love to see the Carina client do something similar, so that I could simply run this:

`eval "$(carina credentials cluster-name)"`

This would be instead of the mult-step process required now (first download the credentials, then source them for use by Docker).

**Comment by rgbkrk** [comment]
Yeah! You *can* do that:

```bash
$ carina credentials test # Non streamlined
#
# Credentials written to "/Users/kyle6475/.carina/clusters/jupyter/test"
#
source "/Users/kyle6475/.carina/clusters/jupyter/test/docker.env"
# Run the command above to get your Docker environment variables set
$ eval "$( carina credentials test )" # woo!
$ docker info
Containers: 3
Images: 2
Role: primary
Strategy: spread
Filters: affinity, health, constraint, port, dependency
Nodes: 1
 62f63f9d-1f5f-45d0-bc43-4f90e9bbdf4a-n1: 104.130.0.242:42376
  └ Containers: 3
  └ Reserved CPUs: 0 / 12
  └ Reserved Memory: 0 B / 4.2 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.18.21-1-rackos, operatingsystem=Debian GNU/Linux 7 (wheezy) (containerized), storagedriver=aufs
CPUs: 12
Total Memory: 4.2 GiB
Name: cb1bb12c9fee
```

**Comment by rgbkrk** [comment]
What this tells me is we need better docs about that. I left out the "tip" version of using `eval "$( carina credentials ...)"` in case the full command included `--api-key`.

**Comment by lowescott** [comment]
Indeed you are correct! I should have realized that...thanks for correcting me, much appreciated.

**Comment by rgbkrk** [comment]
No problem, thanks for reporting. It definitely highlights a sore spot in what we make discoverable and where to trust being able to run `eval "$(...)"`.

There were some other versions of the text in https://github.com/getcarina/carina/issues/32, and I opted to drop it for now until I had a better story including handling spaces in paths, etc.
