### ISSUE TITLE
introduce the concept of a .carina file in ~ to store creds

### ISSUE THREAD

**Issue by diwu1989** [getcarina/carina#49]
the CARINA_APIKEY and CARINA_USERNAME should be stored inside a `.carina` file along with any other config options that this tool will end up having

**Comment by rgbkrk** [comment]
What I've been doing is creating a `~/.carinarc` that has the following:

```bash
export CARINA_USERNAME="rgbkrk@gmail.com"
export CARINA_APIKEY="42a239b7d69725e7"
```

**Comment by beardedprojamz** [comment]
I do the same - but it could probably look for both - a specific config file or env vars.

**Comment by rgbkrk** [comment]
Preferred format? ini style?

**Comment by carolynvs** [comment]
This is now supported in the v2 beta client. https://getcarina.com/betadocs/docs/reference/carina-cli/#profiles.
