### ISSUE TITLE
Specify shell on Windows during carina env

### ISSUE THREAD

**Issue by carolynvs** [getcarina/carina#57]
docker-machine relies on `--shell cmd|powershell` to output appropriate instrtuctions when running `docker-machine env` on Windows. We should do something similar. I don't believe it is possible to detect powershell vs cmd.

**Comment by rgbkrk** [comment]
Sounds good to me.

**Comment by carolynvs** [comment]
I am on vacation next week (if you can call moving to a new house a vacation!), and am hoping to get some free time to start tackling the carina cli on windows issues then.

**Comment by rgbkrk** [comment]
:smile: :dancer: 

Good luck with the :house:!
