### ISSUE TITLE
Listing without clusters is just empty and looks broken

### ISSUE THREAD

**Issue by simonjj** [getcarina/carina#58]
From: https://community.getcarina.com/t/feedback-feature-requests-and-bugs/33/7

It's a very small item but when I run carina list with no clusters in place, the output is:

```
ClusterName Flavor Nodes AutoScale Status
```

Obviously those are just the column headers for the list of clusters but it's confusing to a new user in that there's nothing for them to relate to. My recommendation would be to either display nothing or a message that the user has no clusters yet.

**Comment by rgbkrk** [comment]
The primary motivation for this is that it matches `docker`s output for `ps`:

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

The other big reason is that it's consistently composable. If I'm wrapping `carina` with a shell script and I expect headers to be there, they continue to be there in the same spot.

**Comment by rgbkrk** [comment]
Since we're matching Docker's output here to maintain compatibility, this likely won't change. Feel free to re-open or bring the issue back up.
