### ISSUE TITLE
client is newer than server (client API version: 1.21, server API version: 1.20)

### ISSUE THREAD

**Issue by cdwertmann** [getcarina/carina#60]
Just installed docker tools on my Mac, which provides docker 1.9. Now every docker operation shows:

Error response from daemon: client is newer than server (client API version: 1.21, server API version: 1.20)

Can you upgrade the server side?

**Comment by rgbkrk** [comment]
[We're working on it!](https://getcarina.com/blog/weekly-news-docker-updates/) We have to do auditing with each Docker release and preliminary testing says :soon:.

In the meantime, there are a couple options for you:

* Download the [1.8.3 release](https://github.com/docker/docker/releases/tag/v1.8.3) from Docker themselves, using that directly
* Employ [`dvm`, the docker version manager, to help deal with docker version drift](https://getcarina.com/blog/docker-version-manager/)

**Comment by rgbkrk** [comment]
1.9 shipped on Friday, though this will be a reoccurring issue while we likely lag behind each release.
