### ISSUE TITLE
Use .carina directory on Windows too

### ISSUE THREAD

**Issue by carolynvs** [getcarina/carina#80]
Microsoft has officially blessed using dot folders with their own tools (e.g. dnvm, .net version manager) so we could use it too. 

The only hitch is that if there are windows peeps out there who have already used Carina and downloaded credentials will end up with 2 folders. Since I think the only windows users at the moment are me and don, that shouldn't be much of a problem, just something to document in the release notes.

**Comment by rgbkrk** [comment]
That's definitely my fault. I thought dot folders were weird in Windows in the past and I swear I read some cross platform spec about config that said to use it.

I'd rather use `.carina` everywhere, so a hearty :+1: from me.
