### ISSUE TITLE
Some issues with the windows dvm guide

### ISSUE THREAD

**Issue by zack-shoylev** [getcarina/carina#83]
https://getcarina.com/docs/tutorials/docker-version-manager/

wget is not by default supported on windows. What is a windows native way to do that?

Also when downloading dvm-helper.exe, the script stops with a 404 message for "https://download.getcarina.com/dvm/0.2.2/Windows/$arch/dvm-helper.exe"

**Comment by carolynvs** [comment]
In PowerShell 4.0, both `wget` and `curl` are built-in aliases to Invoke-WebRequest. So it is using native PowerShell commands to download. Are you on an older version perhaps?

**Comment by carolynvs** [comment]
I will look into the download error. Maybe there was a snafu with the latest release...

**Comment by carolynvs** [comment]
Hmm, when I run `iex (wget https://download.getcarina.com/dvm/latest/install.ps1)` I do not have any trouble downloading dvm-helper.exe.

Can you provide more information about your system and how you are downloading the executable?

**Comment by zack-shoylev** [comment]
That is all very strange. Let me post some files

**Comment by zack-shoylev** [comment]
Powershell version:

Major  Minor  Build  Revision
-----  -----  -----  --------
2      0      -1     -1

And can you try the download for the i386 arch?

**Comment by zack-shoylev** [comment]
(it fails to detect x64 so it tries 386 and fails)

**Comment by carolynvs** [comment]
Okay so you are in unsupported land with powershell 2. I've opened bugs against the dvm repo to track.

https://github.com/getcarina/dvm/issues/75
https://github.com/getcarina/dvm/issues/76

**Comment by carolynvs** [comment]
@zack-shoylev I tried to mention you in the new bug but maybe I can't rope you in like that. :-) https://github.com/getcarina/dvm/issues/75#issuecomment-165488232

**Comment by zack-shoylev** [comment]
I think both of these problems might be version related, I will do a few more tests

**Comment by rgbkrk** [comment]
Any word on this one @zack-shoylev?

**Comment by zack-shoylev** [comment]
It was version related. I think this can be closed.
