### ISSUE TITLE
Brew install after download install of Carina CLI mismatches version

### ISSUE THREAD

**Issue by annegentle** [getcarina/carina#87]
Seeing this on Mac OS:

```bash
$ brew upgrade carina
Error: carina 1.0.1 already installed
[annegentle@mbp ~/tools/carina (activetoc *)]$ carina --version
Version: v0.6.0
Commit:  a41bc1ded8a5356494d47308a2f25fafc39231ba
```

Steps to reproduce: 
1. Install carina CLI by downloading from GitHub.
2. Run `brew install carina`.
3. Run `brew upgrade carina`.
4. Run `brew link --overwrite carina`.

My expectations may be off, but I'd expect brew to be able to pick up upgrades once it's linked.

Workaround for now: Delete the directory from `which carina` and then `brew uninstall carina` and `brew install carina`.

**Comment by rgbkrk** [comment]
If you install it by downloading via GitHub and setting that for your path, it's not under control of `brew`. Deleting the manually installed version is definitely the right path here.
